import React from "react";
import { Provider } from "react-redux";

// Import react testing library helpers
import {
	render,
	// fireEvent,
	cleanup,
	waitForElement
} from "react-testing-library";

// Import the navbar component
import { NavBar, NavBarNotConnected } from "components/Navbar/Navbar";
// import from "components/Navbar/Navbar";

/**
 * General note on testing components here. We could at this point
 * test with our without the store. We could also test with a mock
 * store or using our actual store. I've documented all options here.
 *
 * The choice is yours. I think I prefer the sligtly more intergration
 * approach of using store.
 */

/**
 * Option 1: Create the actual store to test from.
 */

import history from "utils/history";
import configureStore from "store/configureStore";

let store;
beforeEach(() => {
	const initialState = {};

	// Create the store
	store = configureStore(initialState, history);
});

/**
 * Option 2: Mock a redux store.
 */

// Import mock for store
// import configureStore from "redux-mock-store";

// let mockStore
// beforeEach(() => {
// 	const middlewares = [];
// 	mockStore = configureStore(middlewares);
// 	store = mockStore({ auth: { loggedIn: false }, router: { location: "/" } });
// });

/**
 * On with the actual tests.
 */

// automatically unmount and cleanup DOM after the test is finished.
afterEach(cleanup);

test("Check that home link exists -- connected to redux", async () => {
	// Render navbar
	const { getByText } = render(
		<Provider store={store}>
			<NavBar />
		</Provider>
	);

	// Act
	await waitForElement(() => getByText(/Home/i));
});

/**
 * Option 3: We test by disconnecting the component. It does however
 * require props galore that were being generated by our store, so
 * we'll create them en-masse
 */

test("Check that home link exists -- not connected to redux", async () => {
	// Props
	const fakeProps = {
		dispatch: console.log,
		loggedIn: false,
		actions: { logoutRequest: console.log }
	};

	// Render navbar
	const { getByText } = render(<NavBarNotConnected {...fakeProps} />);

	// Act
	await waitForElement(() => getByText(/Home/i));
});
